import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { api } from '../lib/api.js'
import { businessMemberships, loadPlatformIdentity, platformAccess, trainerMemberships } from '../lib/platform-role.js'
import { managementModeFromPath, managementRoute } from '../lib/management-path.js'
import { useUI } from '../store/useUI.js'
import Icon from '../components/Icon.jsx'
import ExerciseAdminManager from '../components/ExerciseAdminManager.jsx'
import { Button, Row, Section } from '../components/ui.jsx'

const n = v => new Intl.NumberFormat('uk-UA').format(Number(v || 0))
const cash = (cents, currency='USD') => new Intl.NumberFormat('uk-UA',{style:'currency',currency:String(currency||'USD').toUpperCase(),maximumFractionDigits:2}).format(Number(cents||0)/100)
const date = (v, withTime=false) => v ? (withTime ? new Date(v).toLocaleString('uk-UA') : new Date(v).toLocaleDateString('uk-UA')) : '—'
const inviteOpen = i => !i.revoked_at && Number(i.use_count||0)<Number(i.max_uses||1) && new Date(i.expires_at)>new Date()

function Metric({ value, label, note, onClick }) {
  const inside=<><div className="n">{value ?? '—'}</div><div className="l">{label}</div>{note&&<div className="s">{note}</div>}</>
  return onClick ? <button className="stat" style={{textAlign:'left',color:'inherit',cursor:'pointer'}} onClick={onClick}>{inside}</button> : <div className="stat">{inside}</div>
}

function Bars({ rows=[], field='workouts', money=false }) {
  const vals=rows.map(x=>Number(x?.[field]||0));const max=Math.max(0,...vals)
  if(!rows.length)return <div className="empty">Ще немає даних.</div>
  return <div style={{height:150,display:'flex',alignItems:'flex-end',gap:4,borderBottom:'var(--hair) solid var(--sep)',paddingTop:8}}>{rows.map((x,i)=>{const v=vals[i];const h=max?Math.max(3,Math.round(v/max*100)):2;return <div key={`${x.day||i}:${i}`} title={`${x.day||''} · ${money?cash(v):n(v)}`} style={{height:`${h}%`,flex:1,minWidth:3,borderRadius:'5px 5px 1px 1px',background:'var(--acc)',opacity:v ? .95 : .18}}/>})}</div>
}

function Header({ mode, title, refresh }) {
  const nav=useNavigate();const label={admin:'Адмін',business:'Бізнес',trainer:'Тренер'}[mode]
  return <div className="hdr"><button className="iconbtn" onClick={()=>nav('/settings')}><Icon name="chevronLeft"/></button><div style={{flex:1,marginLeft:10}}><h1>{label} · VARANGYM</h1><div className="sub">{title||'режим керування'}</div></div><button className="iconbtn" onClick={refresh}><Icon name="reset"/></button></div>
}

function ErrorState({ message, retry }) {
  return <div className="narrow"><div className="card"><div className="ttl">Не вдалося завантажити режим керування</div><div className="ss" style={{margin:'6px 0 12px'}}>{message||'Невідома помилка'}</div><Button variant="primary" onClick={retry}>Повторити</Button></div></div>
}

function WorkspacePicker({ spaces, value, setValue }) {
  if((spaces||[]).length<=1)return null
  return <Section title="Workspace">{spaces.map(s=><Row key={`${s.workspace_id}:${s.role}`} icon="personCircle" iconTint={s.workspace_id===value?'var(--acc)':'var(--grey)'} title={s.workspace_name||'Workspace'} subtitle={`${s.workspace_type||''} · ${s.role}`} accessory={s.workspace_id===value?'check':'chevron'} onClick={()=>setValue(s.workspace_id)}/>)}</Section>
}

function ClientView({ client, workspaceId, close }) {
  const [d,setD]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const toast=useUI(s=>s.toast);const id=client.id||client.user_id
  const load=()=>{setError('');api(`/api/analytics/client/${encodeURIComponent(id)}?days=90${workspaceId?`&workspaceId=${encodeURIComponent(workspaceId)}`:''}`).then(setD).catch(e=>setError(e.message||'Помилка'))}
  useEffect(load,[id,workspaceId])
  const assign=async()=>{if(!workspaceId)return toast('Workspace не вибрано');setBusy(true);try{const r=await api('/api/profile-plan/publish',{method:'POST',body:JSON.stringify({workspaceId,clientId:id,name:`${client.display_name||'Client'} · VARANGYM`})});toast(`План призначено · v${r.versionNumber}`);load()}catch(e){toast(e.message||'Не вдалося призначити план')}finally{setBusy(false)}}
  return <><div className="row between" style={{marginBottom:12}}><Button size="sm" onClick={close}>← Назад</Button>{workspaceId&&<Button size="sm" variant="primary" disabled={busy} onClick={assign}>{busy?'…':'Призначити мій план'}</Button>}</div><div className="card"><div className="lbl2">Клієнт</div><div className="big" style={{fontSize:27}}>{client.display_name||d?.client?.display_name||'Client'}</div><div className="ss">{client.email||d?.client?.email||''}</div></div>{error&&<div className="card"><div className="ss">{error}</div><Button size="sm" onClick={load}>Повторити</Button></div>}{!d&&!error&&<div className="empty">Завантаження…</div>}{d&&<><div className="grid2"><Metric value={n(d.summary?.workouts)} label="тренувань / 90д"/><Metric value={n(d.summary?.completed_sets)} label="підходів"/><Metric value={n(Math.round(Number(d.summary?.volume||0)))} label="обсяг"/><Metric value={date(d.summary?.last_workout_at)} label="останнє тренування"/></div><div className="card"><div className="lbl2">Активність · 90 днів</div><Bars rows={d.daily||[]}/></div><Section title="Поточна програма">{d.currentProgram?<Row icon="calendar" iconTint="var(--acc)" title={d.currentProgram.name||'Програма'} subtitle={`v${d.currentProgram.version_number||1} · ${d.currentProgram.trainer_name||''}`} value={`${d.currentProgram.days?.length||0} днів`}/>:<Row title="Програму ще не призначено"/>}</Section><Section title="Останні тренування">{(d.recentWorkouts||[]).slice(0,20).map(w=><Row key={w.id} icon="dumbbell" title={w.name||'Тренування'} subtitle={`${date(w.started_at,true)} · ${n(w.completed_sets)} підходів`} value={n(Math.round(Number(w.volume||0)))}/>)}{!(d.recentWorkouts||[]).length&&<Row title="Історії ще немає"/>}</Section></>}</>
}

function AdminUserView({ user, close }) {
  const [d,setD]=useState(null);const [train,setTrain]=useState(null);const [error,setError]=useState('')
  useEffect(()=>{setError('');Promise.allSettled([api(`/api/admin-insights/user?id=${encodeURIComponent(user.id)}`),api(`/api/analytics/client/${encodeURIComponent(user.id)}?days=90`)]).then(([a,b])=>{if(a.status==='fulfilled')setD(a.value);else setError(a.reason?.message||'Помилка');if(b.status==='fulfilled')setTrain(b.value)})},[user.id])
  if(error)return <><Button size="sm" onClick={close}>← Назад</Button><div className="card"><div className="ss">{error}</div></div></>
  if(!d)return <><Button size="sm" onClick={close}>← Назад</Button><div className="empty">Завантаження…</div></>
  const s=d.sessions?.[0],sub=d.subscriptions?.[0]
  return <><Button size="sm" onClick={close}>← Користувачі</Button><div style={{height:10}}/><div className="card"><div className="lbl2">Акаунт</div><div className="big" style={{fontSize:27}}>{d.user.display_name}</div><div className="ss">{d.user.email||'—'} · {d.user.status} · {d.user.locale}</div></div><div className="grid2"><Metric value={sub?.plan_code||'—'} label="тариф" note={sub?.status}/><Metric value={sub?.trial_ends_at?date(sub.trial_ends_at):'—'} label="trial до"/><Metric value={n(train?.summary?.workouts||d.workouts?.length||0)} label="тренувань"/><Metric value={date(s?.last_seen_at,true)} label="остання активність"/></div><Section title="IP / регіон / пристрій"><Row icon="globe" title={[s?.city,s?.region,s?.country_code].filter(Boolean).join(', ')||'Регіон ще не визначено'} subtitle={s?.ip_hint||'IP недоступний'} value={s?.user_agent?'device':''}/></Section><Section title="Ролі та workspaces">{d.memberships?.length?d.memberships.map((m,i)=><Row key={`${m.workspace_id}:${m.role}:${i}`} icon="personCircle" title={m.workspace} subtitle={`${m.type} · ${m.role}`} value={m.status}/>):<Row title="Memberships немає"/>}</Section><Section title="Підписки">{d.subscriptions?.length?d.subscriptions.map(x=><Row key={x.id} icon="calendar" title={x.plan_code||'—'} subtitle={`${x.status} · ${x.provider}`} value={x.trial_ends_at?`trial ${date(x.trial_ends_at)}`:date(x.current_period_end)}/>):<Row title="Підписок немає"/>}</Section><Section title="Платежі">{d.payments?.length?d.payments.map(p=><Row key={p.id} icon="chart" title={cash(p.amount_cents,p.currency)} subtitle={`${p.status} · ${p.plan_code||''}`} value={date(p.paid_at||p.created_at)}/>):<Row title="Платежів немає"/>}</Section></>
}

function TrainerView({ trainer, workspaceId, close, openClient }) {
  const [d,setD]=useState(null);const [error,setError]=useState('')
  useEffect(()=>{api(`/api/analytics/coach?days=90&workspaceId=${encodeURIComponent(workspaceId)}&trainerId=${encodeURIComponent(trainer.id)}`).then(setD).catch(e=>setError(e.message||'Помилка'))},[trainer.id,workspaceId])
  return <><Button size="sm" onClick={close}>← Команда</Button><div style={{height:10}}/><div className="card"><div className="lbl2">Тренер</div><div className="big" style={{fontSize:27}}>{trainer.display_name}</div><div className="ss">{trainer.email||''}</div></div>{error&&<div className="card"><div className="ss">{error}</div></div>}{!d&&!error&&<div className="empty">Завантаження…</div>}{d&&<><div className="grid2"><Metric value={d.clients?.length||0} label="клієнтів"/><Metric value={n((d.daily||[]).reduce((s,x)=>s+Number(x.workouts||0),0))} label="тренувань / 90д"/></div><div className="card"><div className="lbl2">Активність клієнтів</div><Bars rows={d.daily||[]}/></div><Section title="Клієнти">{(d.clients||[]).map(c=><Row key={c.id} icon="personCircle" title={c.display_name} subtitle={c.email||''} value={`${c.workouts_period||0}/90д`} accessory="chevron" onClick={()=>openClient(c)}/>)}</Section></>}</>
}

function InviteBox({ mode, workspaceId, workspaces, invites, reload }) {
  const toast=useUI(s=>s.toast);const roles=mode==='admin'?[['solo_client','Solo'],['independent_trainer','Тренер'],['organization_owner','Власник бізнесу'],['client','Клієнт workspace'],['trainer','Тренер workspace'],['organization_admin','Адмін workspace']]:mode==='business'?[['client','Клієнт'],['trainer','Тренер'],['organization_admin','Адмін бізнесу']]:[['client','Клієнт']]
  const [role,setRole]=useState(roles[0][0]),[ws,setWs]=useState(workspaceId||''),[created,setCreated]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{if(workspaceId)setWs(workspaceId)},[workspaceId])
  const needsWs=['client','trainer','organization_admin'].includes(role)
  const create=async()=>{if(needsWs&&!ws)return toast('Вибери workspace');setBusy(true);try{const r=await api('/api/invites',{method:'POST',body:JSON.stringify({targetRole:role,workspaceId:needsWs?ws:null,maxUses:1,expiresInDays:7})});setCreated(r.code||'');await reload();toast('Код створено')}catch(e){toast(e.message||'Помилка')}finally{setBusy(false)}}
  const revoke=async i=>{try{await api('/api/invites/revoke',{method:'POST',body:JSON.stringify({id:i.id})});await reload()}catch(e){toast(e.message||'Помилка')}}
  return <><div className="card"><div className="lbl2">Коди доступу та привʼязки</div><div className="ss" style={{margin:'5px 0 12px'}}>Без коду доступний 30-денний trial. Код використовуй, коли акаунт треба одразу привʼязати до потрібного workspace/тренера/ролі.</div><div style={{display:'grid',gap:9}}><select className="field" value={role} onChange={e=>setRole(e.target.value)}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{mode==='admin'&&needsWs&&<select className="field" value={ws} onChange={e=>setWs(e.target.value)}><option value="">— workspace —</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select>}<Button variant="primary" onClick={create} disabled={busy}>{busy?'Створюю…':'Створити одноразовий код · 7 днів'}</Button></div>{created&&<div className="row between" style={{marginTop:12}}><b style={{fontSize:23,letterSpacing:'.08em'}}>{created}</b><Button size="sm" onClick={()=>navigator.clipboard?.writeText(created)}>Копіювати</Button></div>}</div><Section title={`Коди · ${invites.filter(inviteOpen).length} активних`}>{invites.slice(0,30).map(i=><Row key={i.id} icon="key" iconTint={inviteOpen(i)?'var(--acc)':'var(--grey)'} title={i.code||i.target_role} subtitle={`${i.target_role} · ${i.use_count}/${i.max_uses} · до ${date(i.expires_at)}`} value={inviteOpen(i)?'ON':'—'} onClick={()=>inviteOpen(i)&&revoke(i)}/>)}</Section></>
}

function PlanTools({ mode, workspaceId, clients }) {
  const nav=useNavigate();const toast=useUI(s=>s.toast);const [preview,setPreview]=useState(null),[catalog,setCatalog]=useState([]),[q,setQ]=useState(''),[busy,setBusy]=useState(''),[name,setName]=useState('')
  const load=()=>Promise.allSettled([api(`/api/profile-plan/preview?workspaceId=${encodeURIComponent(workspaceId)}`),api(`/api/training/exercises?workspaceId=${encodeURIComponent(workspaceId)}&scope=all&locale=uk&limit=150&q=${encodeURIComponent(q)}`)]).then(([a,b])=>{if(a.status==='fulfilled')setPreview(a.value);if(b.status==='fulfilled')setCatalog(b.value.exercises||[])})
  useEffect(()=>{if(workspaceId)load()},[workspaceId,q])
  const assign=async c=>{const id=c.id||c.user_id;setBusy(id);try{const r=await api('/api/profile-plan/publish',{method:'POST',body:JSON.stringify({workspaceId,clientId:id,name:`${c.display_name||'Client'} · VARANGYM`})});toast(`Призначено · v${r.versionNumber}`)}catch(e){toast(e.message||'Помилка')}finally{setBusy('')}}
  const create=async()=>{if(!name.trim())return;try{await api('/api/training/exercises/custom',{method:'POST',body:JSON.stringify({workspaceId,name:name.trim(),locale:'uk',ownerScope:mode==='business'?'organization':'trainer'})});setName('');load();toast('Вправу створено')}catch(e){toast(e.message||'Помилка')}}
  return <><div className="card"><div className="row between" style={{alignItems:'flex-start',gap:10}}><div><div className="lbl2">Поточний робочий план</div><div className="big" style={{fontSize:24}}>{preview?.days?.length||0} днів</div><div className="ss">Редагуєш його у стандартній вкладці План, а тут призначаєш клієнтам.</div></div><Button size="sm" onClick={()=>nav('/plan')}>Редагувати</Button></div></div><Section title="Призначити клієнту">{clients.length?clients.map(c=>{const id=c.id||c.user_id;return <Row key={id} icon="personCircle" title={c.display_name} subtitle={c.email||''}><Button size="sm" disabled={busy===id} onClick={()=>assign(c)}>{busy===id?'…':'Призначити'}</Button></Row>}):<Row title="Клієнтів немає"/>}</Section><div className="card"><div className="lbl2">Створити власну вправу</div><div className="row" style={{gap:8,marginTop:9}}><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Назва"/><Button size="sm" variant="primary" onClick={create}>+</Button></div><div className="search" style={{marginTop:10}}><Icon name="magnifier"/><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Пошук у каталозі…"/></div></div><Section title={`Каталог · ${catalog.length}`}>{catalog.slice(0,100).map(ex=><Row key={ex.id} icon="dumbbell" iconTint={ex.owner_scope==='platform'?'var(--grey)':'var(--acc)'} title={ex.name} subtitle={`${ex.primary_muscle_key||''} · ${ex.equipment_key||''}`} value={ex.owner_scope==='platform'?'VARANGYM':'Власна'}/>)}</Section></>
}

export default function ManagementModeV2() {
  const loc=useLocation(),nav=useNavigate(),toast=useUI(s=>s.toast);const route=managementModeFromPath(loc.pathname)||{mode:'trainer',section:'dashboard'};const {mode,section}=route
  const [identity,setIdentity]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[overview,setOverview]=useState(null),[analytics,setAnalytics]=useState(null),[billing,setBilling]=useState(null),[plans,setPlans]=useState([]),[invites,setInvites]=useState([]),[insights,setInsights]=useState(null),[workspaces,setWorkspaces]=useState([]),[workspaceId,setWorkspaceId]=useState(''),[clients,setClients]=useState([]),[detail,setDetail]=useState(null),[showCodes,setShowCodes]=useState(false),[financeDetail,setFinanceDetail]=useState('')
  const access=useMemo(()=>platformAccess(identity),[identity]);const trainerSpaces=useMemo(()=>trainerMemberships(identity),[identity]);const businessSpaces=useMemo(()=>businessMemberships(identity),[identity]);const spaces=mode==='business'?businessSpaces:trainerSpaces;const allowed=identity&&((mode==='admin'&&access.platformAdmin)||(mode==='business'&&access.business)||(mode==='trainer'&&access.trainer));const current=spaces.find(x=>x.workspace_id===workspaceId)||spaces[0]

  const load=async()=>{setLoading(true);setError('');try{const me=identity||await loadPlatformIdentity();if(!identity)setIdentity(me);const ac=platformAccess(me);if(!((mode==='admin'&&ac.platformAdmin)||(mode==='business'&&ac.business)||(mode==='trainer'&&ac.trainer))){setError('Цей акаунт не має доступу до вибраного режиму.');return}
    if(mode==='admin'){const r=await Promise.allSettled([api('/api/admin/overview'),api('/api/admin/workspaces'),api('/api/analytics/admin?days=30'),api('/api/billing/admin/summary'),api('/api/invites'),api('/api/admin-insights/summary')]);setOverview(r[0].status==='fulfilled'?r[0].value:{});const ws=r[1].status==='fulfilled'?r[1].value.workspaces||[]:[];setWorkspaces(ws);setAnalytics(r[2].status==='fulfilled'?r[2].value:null);setBilling(r[3].status==='fulfilled'?r[3].value:null);setInvites(r[4].status==='fulfilled'?r[4].value.invites||[]:[]);const ins=r[5].status==='fulfilled'?r[5].value:null;setInsights(ins);setPlans(ins?.plans||[]);if(!workspaceId&&ws.length)setWorkspaceId(ws[0].id)}
    else {const sp=mode==='business'?businessMemberships(me):trainerMemberships(me);const wid=workspaceId||sp[0]?.workspace_id;if(!wid)throw new Error('Немає workspace для цього режиму');if(!workspaceId)setWorkspaceId(wid);const r=await Promise.allSettled([mode==='business'?api(`/api/business/overview?workspaceId=${wid}`):api(`/api/coach/clients?workspaceId=${wid}`),mode==='business'?api(`/api/analytics/business?days=30&workspaceId=${wid}`):api(`/api/analytics/coach?days=30&workspaceId=${wid}`),api(`/api/coach/clients?workspaceId=${wid}`),api(`/api/invites?workspaceId=${wid}`),api('/api/billing/me'),api('/api/billing/plans')]);setOverview(r[0].status==='fulfilled'?r[0].value:{});setAnalytics(r[1].status==='fulfilled'?r[1].value:null);setClients(r[2].status==='fulfilled'?r[2].value.clients||[]:[]);setInvites(r[3].status==='fulfilled'?r[3].value.invites||[]:[]);setBilling(r[4].status==='fulfilled'?r[4].value:null);setPlans(r[5].status==='fulfilled'?r[5].value.plans||[]:[])}
  }catch(e){setError(e.message||'Помилка')}finally{setLoading(false)}}
  useEffect(()=>{setDetail(null);setShowCodes(false);setFinanceDetail('');load() /* eslint-disable-next-line react-hooks/exhaustive-deps */},[mode,workspaceId])

  if(!identity&&loading)return <div className="narrow"><div className="empty">Завантаження режиму керування…</div></div>
  if(!identity&&error)return <ErrorState message={error} retry={load}/>
  if(identity&&!allowed&&!loading)return <ErrorState message={error||'Немає доступу до цього режиму.'} retry={()=>nav('/settings')}/>

  const title=mode==='admin'?'Вся платформа':current?.workspace_name||overview?.workspace?.name||identity?.user?.display_name;const adminUsers=insights?.directory||[],f=insights?.finance||{},trainers=overview?.trainers||[],stats=overview?.stats||{}
  const wsBilling=billing?.workspaceBilling?.find(x=>x.workspace_id===workspaceId),wsSub=(billing?.workspaceSubscriptions||[]).filter(x=>x.workspace_id===workspaceId).sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0))[0],planCode=wsBilling?.plan_code||wsSub?.plan_code||'—',plan=plans.find(x=>x.code===planCode),clientLimit=plan?.client_limit,price=plan?cash(plan.price_cents,plan.currency):'—'

  const closeDetail=()=>setDetail(null)
  if(detail?.type==='client')return <div className="narrow"><Header mode={mode} title={title} refresh={load}/><ClientView client={detail.value} workspaceId={detail.workspaceId||workspaceId} close={closeDetail}/></div>
  if(detail?.type==='user')return <div className="narrow"><Header mode={mode} title="Користувач" refresh={load}/><AdminUserView user={detail.value} close={closeDetail}/></div>
  if(detail?.type==='trainer')return <div className="narrow"><Header mode={mode} title={title} refresh={load}/><TrainerView trainer={detail.value} workspaceId={workspaceId} close={closeDetail} openClient={c=>setDetail({type:'client',value:c,workspaceId})}/></div>

  const adminFinance=financeDetail&&<Section title="Деталізація фінансів">{(insights?.subjects||[]).filter(s=>financeDetail==='trials'?s.subscription_status==='trialing':financeDetail==='subs'?s.subscription_status==='active':true).map((s,i)=><Row key={`${s.subject_type}:${s.subject_id}:${i}`} icon="chart" title={s.subject_name||s.billing_email||'Subject'} subtitle={`${s.plan_code||'—'} · ${s.subscription_status||'configured'}${s.trial_ends_at?` · trial до ${date(s.trial_ends_at)}`:''}`} value={cash(s.paid_cents)}/>)}</Section>

  return <div className="narrow"><Header mode={mode} title={title} refresh={load}/>{mode!=='admin'&&<WorkspacePicker spaces={spaces} value={workspaceId} setValue={setWorkspaceId}/>} {error&&<div className="card"><div className="ss">{error}</div><Button size="sm" onClick={load}>Повторити</Button></div>}{loading&&!overview&&<div className="empty">Завантаження…</div>}

    {section==='home'&&<><div className="card"><div className="lbl2">{mode==='admin'?'VARANGYM Platform':mode==='business'?'Бізнес-профіль':'Тренерський профіль'}</div><div className="big" style={{fontSize:25}}>{title}</div><div className="ss">Це окремий робочий режим у тому самому VARANGYM. Звичайний режим тренувань не змінено.</div></div>{mode==='admin'?<div className="grid2"><Metric value={n(adminUsers.length)} label="користувачів"/><Metric value={n(f.active_subscriptions)} label="підписок"/><Metric value={cash(f.mrr_cents)} label="MRR"/><Metric value={invites.filter(inviteOpen).length} label="активних кодів"/></div>:<div className="grid2"><Metric value={planCode} label="поточний тариф" note={wsSub?.status}/><Metric value={price} label="вартість / місяць"/><Metric value={clientLimit==null?n(clients.length):`${clients.length} / ${clientLimit}`} label="клієнтів у плані"/><Metric value={wsSub?.trial_ends_at?date(wsSub.trial_ends_at):'—'} label="trial до"/></div>}<div className="grid2"><Button onClick={()=>setShowCodes(v=>!v)}>Коди доступу</Button><Button onClick={()=>nav('/settings')}>Підписка / налаштування</Button></div>{showCodes&&<InviteBox mode={mode} workspaceId={workspaceId} workspaces={workspaces} invites={invites} reload={load}/>} {mode==='admin'&&<Section title="Workspaces">{workspaces.slice(0,20).map(w=><Row key={w.id} icon="personCircle" title={w.name} subtitle={`${w.type} · ${w.members||0} учасників`} value={`${w.trainers||0}/${w.clients||0}`}/>)}</Section>}</>}

    {section==='people'&&<>{mode==='admin'?<Section title={`Всі користувачі · ${adminUsers.length}`}>{adminUsers.map(u=><Row key={u.id} icon="personCircle" iconTint={u.is_platform_admin?'var(--acc)':'var(--blue)'} title={u.display_name} subtitle={`${u.email||'—'} · ${u.direct_plan||u.managed_plans?.[0]?.planCode||'без тарифу'} · ${[u.city,u.region,u.country_code].filter(Boolean).join(', ')||u.last_ip||'гео —'}`} value={`${u.workouts_30d||0}/30д`} accessory="chevron" onClick={()=>setDetail({type:'user',value:u})}/>)}</Section>:mode==='business'?<><Section title={`Тренери · ${trainers.length}`}>{trainers.map(t=><Row key={t.id} icon="personCircle" iconTint="var(--indigo)" title={t.display_name} subtitle={t.email||''} value={`${t.clients||0} клієнтів`} accessory="chevron" onClick={()=>setDetail({type:'trainer',value:t})}/>)}</Section><Section title={`Клієнти · ${clients.length}`}>{clients.map(c=><Row key={c.id||c.user_id} icon="personCircle" title={c.display_name} subtitle={`${c.trainer_name||'клієнт'} · ${c.workouts_30d||0} тренувань`} value={date(c.last_workout_at)} accessory="chevron" onClick={()=>setDetail({type:'client',value:c,workspaceId})}/>)}</Section></>:<Section title={`Мої клієнти · ${clients.length}`}>{clients.map(c=><Row key={c.id||c.user_id} icon="personCircle" title={c.display_name} subtitle={`${c.email||''} · ${c.workouts_30d||0} тренувань / 30д`} value={date(c.last_workout_at)} accessory="chevron" onClick={()=>setDetail({type:'client',value:c,workspaceId})}/>)}</Section>}</>}

    {section==='dashboard'&&<>{mode==='admin'?<><div className="grid2"><Metric value={cash(f.mrr_cents)} label="MRR" note="регулярний місячний дохід" onClick={()=>setFinanceDetail('all')}/><Metric value={cash(f.arr_cents)} label="ARR" onClick={()=>setFinanceDetail('all')}/><Metric value={cash(f.revenue_month_cents)} label="дохід цього місяця" onClick={()=>setFinanceDetail('all')}/><Metric value={cash(f.revenue_lifetime_cents)} label="дохід за весь час" onClick={()=>setFinanceDetail('all')}/><Metric value={n(f.active_subscriptions)} label="активних підписок" onClick={()=>setFinanceDetail('subs')}/><Metric value={n(f.active_trials)} label="активних trial" note={`${n(f.trials_expiring_7d)} завершаться ≤7 днів`} onClick={()=>setFinanceDetail('trials')}/><Metric value={cash(f.avg_payment_cents)} label="середній платіж" onClick={()=>setFinanceDetail('all')}/><Metric value={cash(f.arppu_cents)} label="ARPPU / 30д" onClick={()=>setFinanceDetail('all')}/></div><div className="card"><div className="lbl2">Дохід · 90 днів</div><Bars rows={insights?.dailyRevenue||[]} field="cents" money/></div>{adminFinance}<Section title="Тарифи">{plans.map(p=><Row key={p.code} icon="chart" title={p.metadata?.label||p.code} subtitle={`${p.audience} · ${p.billing_kind}`} value={`${cash(p.price_cents,p.currency)}${p.interval_unit==='month'?'/міс':''}`}/>)}</Section></>:<><div className="grid2"><Metric value={clients.length||stats.clients||0} label="клієнтів" onClick={()=>nav(managementRoute(mode,'people'))}/><Metric value={mode==='business'?(stats.trainers??trainers.length):(analytics?.clients?.length??clients.length)} label={mode==='business'?'тренерів':'активна база'} onClick={()=>nav(managementRoute(mode,'people'))}/><Metric value={n((analytics?.daily||[]).reduce((sum,x)=>sum+Number(x.workouts||0),0))} label="тренувань / 30д" onClick={()=>nav(managementRoute(mode,'stats'))}/><Metric value={mode==='business'?cash(analytics?.revenue?.period_cents):price} label={mode==='business'?'дохід / 30д':'вартість плану'} onClick={()=>nav('/settings')}/></div><div className="card"><div className="lbl2">Активність · 30 днів</div><Bars rows={analytics?.daily||[]}/></div></>}</>}

    {section==='stats'&&<><div className="card"><div className="lbl2">Тренувальна статистика</div><div className="ss">Натисни на користувача або клієнта — відкриється його прогрес, програма й історія.</div><Bars rows={analytics?.daily||[]}/></div>{mode==='admin'?<Section title="Найактивніші · 30 днів">{adminUsers.slice().sort((a,b)=>Number(b.workouts_30d||0)-Number(a.workouts_30d||0)).slice(0,50).map(u=><Row key={u.id} icon="chartLine" title={u.display_name} subtitle={u.email||''} value={`${u.workouts_30d||0}/30д`} accessory="chevron" onClick={()=>setDetail({type:'user',value:u})}/>)}</Section>:<Section title="Клієнти">{clients.slice().sort((a,b)=>Number(b.workouts_30d||b.workouts_period||0)-Number(a.workouts_30d||a.workouts_period||0)).map(c=><Row key={c.id||c.user_id} icon="chartLine" title={c.display_name} subtitle={c.trainer_name||c.email||''} value={`${c.workouts_30d||c.workouts_period||0}/30д`} accessory="chevron" onClick={()=>setDetail({type:'client',value:c,workspaceId})}/>)}</Section>}</>}

    {section==='exercises'&&(mode==='admin'?<ExerciseAdminManager/>:<PlanTools mode={mode} workspaceId={workspaceId} clients={clients}/>)}
  </div>
}
