import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { api } from '../lib/api.js'
import { loadPlatformIdentity, platformAccess, trainerMemberships, businessMemberships } from '../lib/platform-role.js'
import { setRoleMode, viewOf } from '../lib/role-mode.js'
import { loadExerciseOverrides } from '../lib/exercise-overrides.js'
import { useUI } from '../store/useUI.js'
import Icon from '../components/Icon.jsx'
import { Button, Row, Section, Segmented, Switch } from '../components/ui.jsx'

const money=(cents,currency='USD')=>new Intl.NumberFormat('uk-UA',{style:'currency',currency,maximumFractionDigits:2}).format(Number(cents||0)/100)
const num=v=>new Intl.NumberFormat('uk-UA').format(Number(v||0))
const date=v=>{if(!v)return'—';try{return new Date(v).toLocaleDateString('uk-UA')}catch{return'—'}}
const dt=v=>{if(!v)return'—';try{return new Date(v).toLocaleString('uk-UA')}catch{return'—'}}
const activeInvite=i=>!i.revoked_at&&Number(i.use_count||0)<Number(i.max_uses||1)&&new Date(i.expires_at).getTime()>Date.now()

function Metric({label,value,note,onClick}){const Tag=onClick?'button':'div';return <Tag className="stat" onClick={onClick} style={onClick?{textAlign:'left',width:'100%',cursor:'pointer'}:undefined}><div className="n">{value}</div><div className="l">{label}</div>{note&&<div className="s">{note}</div>}</Tag>}
function Bars({rows=[]}){const vals=rows.map(x=>Number(x.workouts||0)),max=Math.max(1,...vals);return <div style={{height:140,display:'flex',alignItems:'flex-end',gap:4,borderBottom:'var(--hair) solid var(--sep)',paddingTop:10}}>{rows.map((x,i)=><div key={`${x.day}:${i}`} title={`${x.day}: ${x.workouts}`} style={{flex:1,minWidth:3,height:`${x.workouts?Math.max(4,Math.round(Number(x.workouts)*100/max)):2}%`,borderRadius:'5px 5px 1px 1px',background:'var(--acc)',opacity:x.workouts?.9:.2}} />)}</div>}
function ErrorBox({text,retry}){return <div className="card"><div className="ttl">Не вдалося завантажити дані</div><div className="ss" style={{margin:'6px 0 12px'}}>{text}</div><Button onClick={retry}>Повторити</Button></div>}

function SubscriptionBadge({status,plan}){return <span className={'tag '+(status==='active'||status==='trialing'?'acc':'')}>{plan||'без плану'}{status?` · ${status}`:''}</span>}

function ClientDetail({client,workspaceId,onBack}){
  const [d,setD]=useState(null),[err,setErr]=useState('')
  useEffect(()=>{setD(null);setErr('');api(`/api/analytics/client/${encodeURIComponent(client.id||client.user_id)}?days=90&workspaceId=${encodeURIComponent(workspaceId)}`).then(setD).catch(e=>setErr(e.message))},[client,workspaceId])
  return <>
    <Button size="sm" onClick={onBack}>← Назад</Button>
    <div className="card" style={{marginTop:12}}><div className="lbl2">Клієнт</div><div className="big" style={{fontSize:27}}>{client.display_name||client.name||'Клієнт'}</div><div className="ss">{client.email||''}</div></div>
    {err&&<ErrorBox text={err} retry={()=>location.reload()} />}
    {!d&&!err&&<div className="empty">Завантаження…</div>}
    {d&&<><div className="grid2"><Metric value={num(d.summary?.workouts)} label="тренувань / 90 днів"/><Metric value={num(d.summary?.completed_sets)} label="підходів"/><Metric value={num(Math.round(Number(d.summary?.volume||0)))} label="обсяг"/><Metric value={date(d.summary?.last_workout_at)} label="останнє тренування"/></div><div className="card"><div className="lbl2">Динаміка тренувань</div><Bars rows={d.daily||[]}/></div><Section title="Поточна програма">{d.currentProgram?<Row icon="calendar" iconTint="var(--acc)" title={d.currentProgram.name||'Програма'} subtitle={`v${d.currentProgram.version_number||1} · ${d.currentProgram.trainer_name||''}`} value={`${d.currentProgram.days?.length||0} днів`}/>:<Row title="Програма не призначена"/>}</Section><Section title="Останні тренування">{(d.recentWorkouts||[]).slice(0,12).map(w=><Row key={w.id} icon="dumbbell" title={w.name||'Тренування'} subtitle={`${dt(w.started_at)} · ${w.completed_sets||0} підходів`} value={num(Math.round(Number(w.volume||0)))}/>)}</Section></>}
  </>
}

function InviteBox({mode,workspaceId,workspaces=[],invites=[],reload}){
  const toast=useUI(s=>s.toast);const [role,setRole]=useState(mode==='trainer'?'client':mode==='business'?'client':'solo_client');const [email,setEmail]=useState('');const [workspace,setWorkspace]=useState(workspaceId||'');const [busy,setBusy]=useState(false);const [last,setLast]=useState(null)
  useEffect(()=>{if(workspaceId)setWorkspace(workspaceId)},[workspaceId])
  const roleOptions=mode==='trainer'?[['client','Клієнт']]:mode==='business'?[['client','Клієнт'],['trainer','Тренер'],['organization_admin','Адмін організації']]:[['solo_client','Solo'],['independent_trainer','Тренер'],['organization_owner','Бізнес'],['client','Клієнт workspace'],['trainer','Тренер workspace'],['platform_admin','Адмін платформи']]
  const needsWs=['client','trainer','organization_admin'].includes(role)
  const create=async()=>{if(needsWs&&!workspace)return toast('Вибери workspace');setBusy(true);try{const d=await api('/api/invites',{method:'POST',body:JSON.stringify({targetRole:role,workspaceId:needsWs?workspace:null,email:email.trim()||null,maxUses:1,expiresInDays:7})});setLast(d.code);toast('Код створено');await reload?.()}catch(e){toast(e.message)}finally{setBusy(false)}}
  return <div className="card"><div className="lbl2">Код привʼязки</div><div className="ss" style={{margin:'5px 0 12px'}}>Для команди й клієнтів коди залишаються: вони визначають, до кого саме привʼязати новий акаунт.</div><div style={{display:'grid',gap:9}}><select className="field" value={role} onChange={e=>setRole(e.target.value)}>{roleOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{needsWs&&mode==='admin'&&<select className="field" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">Workspace…</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select>}<input className="field" type="email" placeholder="Email (необовʼязково)" value={email} onChange={e=>setEmail(e.target.value)}/><Button variant="primary" icon="plus" disabled={busy} onClick={create}>{busy?'Створюю…':'Створити код'}</Button>{last&&<button className="card" style={{fontSize:24,fontWeight:800,letterSpacing:'.08em',cursor:'pointer'}} onClick={()=>navigator.clipboard?.writeText(last).then(()=>toast('Скопійовано'))}>{last}</button>}</div><div className="ss" style={{marginTop:10}}>{invites.filter(activeInvite).length} активних кодів</div></div>
}

function PlanAssign({workspaceId,clients=[]}){
  const toast=useUI(s=>s.toast),nav=useNavigate();const [preview,setPreview]=useState(null),[busy,setBusy]=useState('')
  useEffect(()=>{if(workspaceId)api(`/api/profile-plan/preview?workspaceId=${encodeURIComponent(workspaceId)}`).then(setPreview).catch(()=>setPreview({days:[]}))},[workspaceId])
  const assign=async c=>{const id=c.id||c.user_id;setBusy(id);try{const d=await api('/api/profile-plan/publish',{method:'POST',body:JSON.stringify({workspaceId,clientId:id,name:`${c.display_name||'Client'} · VARANGYM`})});toast(`План призначено · v${d.versionNumber}`)}catch(e){toast(e.message)}finally{setBusy('')}}
  return <><div className="card"><div className="row between"><div><div className="lbl2">Шаблон плану</div><div className="big" style={{fontSize:23}}>{preview?.days?.length||0} тренувальних днів</div><div className="ss">Редагування — у стандартному редакторі VARANGYM.</div></div><Button size="sm" onClick={()=>nav('/plan')}>Редагувати</Button></div></div><Section title="Призначити план клієнту">{clients.map(c=><Row key={c.id||c.user_id} icon="personCircle" title={c.display_name||'Клієнт'} subtitle={c.email||''}><Button size="sm" disabled={busy===(c.id||c.user_id)} onClick={()=>assign(c)}>Призначити</Button></Row>)}</Section></>
}

function ExerciseAdmin(){
  const toast=useUI(s=>s.toast);const [q,setQ]=useState(''),[locale,setLocale]=useState('uk'),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false)
  const load=()=>api(`/api/insights/exercises?locale=${encodeURIComponent(locale)}&q=${encodeURIComponent(q)}&limit=150`).then(d=>setRows(d.exercises||[])).catch(e=>toast(e.message))
  useEffect(load,[locale])
  const save=async()=>{if(!selected)return;setBusy(true);try{await api(`/api/insights/exercises/${selected.id}`,{method:'PATCH',body:JSON.stringify({active:selected.active,equipment:selected.equipment_key,primaryMuscle:selected.primary_muscle_key,image:selected.metadata?.image||null,gif:selected.metadata?.gif||null,translations:selected.translations})});toast('Вправу оновлено');await loadExerciseOverrides();await load();setSelected(null)}catch(e){toast(e.message)}finally{setBusy(false)}}
  const setTr=(lang,key,val)=>setSelected(s=>({...s,translations:{...(s.translations||{}),[lang]:{...(s.translations?.[lang]||{}),[key]:val}}}))
  if(selected)return <><Button size="sm" onClick={()=>setSelected(null)}>← Вправи</Button><div className="card" style={{marginTop:12}}><div className="lbl2">Редактор вправи</div><div className="ss">ID: {selected.legacy_key}</div><div style={{display:'grid',gap:10,marginTop:12}}><label className="row between">Доступна всім <Switch checked={selected.active!==false} onChange={v=>setSelected(s=>({...s,active:v}))}/></label>{['uk','ru','en'].map(lang=><div key={lang}><div className="small muted" style={{marginBottom:5}}>{lang.toUpperCase()} назва</div><input className="field" value={selected.translations?.[lang]?.name||''} onChange={e=>setTr(lang,'name',e.target.value)} placeholder={lang==='uk'?'Популярна назва в Україні':lang==='ru'?'Популярна назва в Росії':'English name'}/><textarea className="field" rows="3" style={{marginTop:7}} value={selected.translations?.[lang]?.description||''} onChange={e=>setTr(lang,'description',e.target.value)} placeholder="Опис"/></div>)}<input className="field" value={selected.metadata?.gif||''} onChange={e=>setSelected(s=>({...s,metadata:{...(s.metadata||{}),gif:e.target.value}}))} placeholder="GIF path / URL"/><input className="field" value={selected.metadata?.image||''} onChange={e=>setSelected(s=>({...s,metadata:{...(s.metadata||{}),image:e.target.value}}))} placeholder="Image path / URL"/><input className="field" value={selected.equipment_key||''} onChange={e=>setSelected(s=>({...s,equipment_key:e.target.value}))} placeholder="Обладнання"/><input className="field" value={selected.primary_muscle_key||''} onChange={e=>setSelected(s=>({...s,primary_muscle_key:e.target.value}))} placeholder="Основний мʼяз"/><Button variant="primary" disabled={busy} onClick={save}>{busy?'Зберігаю…':'Зберегти зміни'}</Button></div></div></>
  return <><div className="card"><div className="lbl2">Керування вправами</div><div className="ss">Адмін може виправити назву UK/RU/EN, опис, GIF/зображення, обладнання та глобально приховати вправу.</div><div className="row" style={{gap:8,marginTop:12}}><input className="field" style={{flex:1}} placeholder="Пошук…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><Button size="sm" onClick={load}>Знайти</Button></div><div style={{marginTop:8}}><Segmented options={[{value:'uk',label:'UA'},{value:'ru',label:'RU'},{value:'en',label:'EN'}]} value={locale} onChange={setLocale}/></div></div><Section title={`Вправи · ${rows.length}`}>{rows.map(x=><Row key={x.id} icon="dumbbell" iconTint={x.active?'var(--acc)':'var(--grey)'} title={x.name||x.legacy_key} subtitle={`${x.equipment_key||'—'} · ${x.primary_muscle_key||'—'}${x.active?'':' · прихована'}`} accessory="chevron" onClick={()=>setSelected(x)}/>)}</Section></>
}

function AdminConsole({view,data,analytics,invites,reload}){
  const [detail,setDetail]=useState(''),[user,setUser]=useState(null);const s=data?.summary||{};const users=data?.users||[],spaces=data?.workspaces||[]
  if(user)return <><Button size="sm" onClick={()=>setUser(null)}>← Користувачі</Button><div className="card" style={{marginTop:12}}><div className="lbl2">Користувач</div><div className="big" style={{fontSize:27}}>{user.display_name}</div><div className="ss">{user.email||'без email'}</div></div><Section title="Акаунт"><Row title="Підписка" value={<SubscriptionBadge plan={user.plan_code} status={user.subscription_status}/>}/><Row title="Trial до" value={date(user.trial_ends_at)}/><Row title="Останній вхід" value={dt(user.last_seen_at)}/><Row title="IP останньої сесії" value={user.last_ip||'—'}/><Row title="Пристрій" subtitle={user.user_agent||'—'}/><Row title="Тренувань / 30 днів" value={user.workouts_30d||0}/>{user.workspace&&<Row title="Workspace" subtitle={`${user.workspace.type} · ${user.workspace.name}`}/>}</Section></>
  if(view==='home')return <><div className="card"><div className="lbl2">VARANGYM · Admin</div><div className="big" style={{fontSize:26}}>Платформа</div><div className="ss">Короткий стан бізнесу, користувачів і тренувань.</div></div><div className="grid2"><Metric value={num(s.users)} label="користувачів" note={`${num(s.active30)} активні / 30д`}/><Metric value={money(s.mrrCents)} label="MRR"/><Metric value={num(s.activeSubscriptions)} label="платних підписок"/><Metric value={num(s.trials)} label="активних trial"/></div><div className="card"><div className="lbl2">Активність / 30 днів</div><Bars rows={analytics?.daily||[]}/></div><Section title="Останні користувачі">{users.slice(0,6).map(u=><Row key={u.id} icon="personCircle" title={u.display_name} subtitle={u.plan_code?`${u.plan_code} · ${u.subscription_status||'—'}`:'без підписки'} value={date(u.created_at)} accessory="chevron" onClick={()=>setUser(u)}/>)}</Section></>
  if(view==='people')return <><Section title={`Користувачі · ${users.length}`}>{users.map(u=><Row key={u.id} icon="personCircle" iconTint={u.is_platform_admin?'var(--acc)':'var(--blue)'} title={u.display_name} subtitle={`${u.email||'без email'} · ${u.plan_code||'без плану'} · ${u.subscription_status||'—'}`} value={u.last_ip||'—'} accessory="chevron" onClick={()=>setUser(u)}/>)}</Section><Section title={`Організації / workspaces · ${spaces.length}`}>{spaces.map(w=><Row key={w.id} icon="personCircle" title={w.name} subtitle={`${w.type} · ${w.members} учасників`} value={`${w.trainers} / ${w.clients}`}/>)}</Section><InviteBox mode="admin" workspaces={spaces} invites={invites} reload={reload}/></>
  if(view==='dashboard'){const subs=data?.subscriptions||[],payments=data?.payments||[];const filtered=detail==='trials'?subs.filter(x=>x.status==='trialing'):detail==='subs'?subs.filter(x=>x.status==='active'):null;return <><div className="grid2"><Metric value={money(s.monthRevenueCents)} label="дохід цього місяця" onClick={()=>setDetail('payments')}/><Metric value={money(s.lifetimeRevenueCents)} label="дохід за весь час" onClick={()=>setDetail('payments')}/><Metric value={money(s.mrrCents)} label="MRR" onClick={()=>setDetail('subs')}/><Metric value={money(s.arpuCents)} label="ARPU / активна підписка" onClick={()=>setDetail('subs')}/><Metric value={num(s.activeSubscriptions)} label="активні підписки" onClick={()=>setDetail('subs')}/><Metric value={num(s.trials)} label="trial" onClick={()=>setDetail('trials')}/></div>{detail==='payments'&&<Section title="Останні платежі">{payments.slice(0,50).map(p=><Row key={p.id} icon="creditCard" title={p.user_name||p.workspace_name||p.plan_code||'Payment'} subtitle={`${p.plan_code||''} · ${p.status} · ${dt(p.paid_at||p.created_at)}`} value={money(p.amount_cents,p.currency)}/>)}</Section>}{filtered&&<Section title={detail==='trials'?'Trial підписки':'Активні підписки'}>{filtered.map(x=><Row key={x.id} icon="creditCard" title={x.plan_metadata?.label||x.plan_code} subtitle={`${x.subject_type} · ${x.status}`} value={date(x.trial_ends_at||x.current_period_end)}/>)}</Section>}</>}
  if(view==='stats')return <><div className="grid2"><Metric value={num((analytics?.daily||[]).reduce((n,x)=>n+Number(x.workouts||0),0))} label="тренувань / 30д"/><Metric value={num(analytics?.users?.active_30d||0)} label="активних користувачів"/></div><div className="card"><div className="lbl2">Тренування платформи</div><Bars rows={analytics?.daily||[]}/></div><Section title="Користувачі · відкрити профіль прогресу">{users.filter(u=>u.workouts_30d>0).slice(0,100).map(u=><Row key={u.id} icon="chart" title={u.display_name} subtitle={`${u.workouts_30d} тренувань / 30д`} accessory="chevron" onClick={()=>setUser(u)}/>)}</Section></>
  return <ExerciseAdmin/>
}

function TrainerConsole({view,workspaceId,overview,analytics,invites,reload}){const [client,setClient]=useState(null);const clients=overview?.clients||[];if(client)return <ClientDetail client={client} workspaceId={workspaceId} onBack={()=>setClient(null)}/>;if(view==='home')return <><div className="card"><div className="lbl2">VARANGYM · Coach</div><div className="big" style={{fontSize:26}}>Мої клієнти</div><div className="ss">Швидкий огляд роботи тренера.</div></div><div className="grid2"><Metric value={clients.length} label="клієнтів"/><Metric value={num((analytics?.daily||[]).reduce((n,x)=>n+Number(x.workouts||0),0))} label="тренувань / 30д"/><Metric value={invites.filter(activeInvite).length} label="активних кодів"/><Metric value={clients.filter(c=>c.workouts_7d>0).length} label="активні / 7д"/></div><Section title="Остання активність">{clients.slice(0,8).map(c=><Row key={c.id||c.user_id} icon="personCircle" title={c.display_name} subtitle={`${c.workouts_period||c.workouts_30d||0} тренувань / 30д`} value={date(c.last_workout_at)} accessory="chevron" onClick={()=>setClient(c)}/>)}</Section></>;if(view==='people')return <><Section title={`Клієнти · ${clients.length}`}>{clients.map(c=><Row key={c.id||c.user_id} icon="personCircle" title={c.display_name} subtitle={c.email||''} value={`${c.workouts_period||c.workouts_30d||0} / 30д`} accessory="chevron" onClick={()=>setClient(c)}/>)}</Section><InviteBox mode="trainer" workspaceId={workspaceId} invites={invites} reload={reload}/></>;if(view==='dashboard')return <PlanAssign workspaceId={workspaceId} clients={clients}/>;if(view==='stats')return <><div className="card"><div className="lbl2">Активність клієнтів</div><Bars rows={analytics?.daily||[]}/></div><Section title="Прогрес клієнтів">{clients.map(c=><Row key={c.id||c.user_id} icon="chart" title={c.display_name} subtitle={`${c.workouts_7d||0} тренувань / 7д`} value={date(c.last_workout_at)} accessory="chevron" onClick={()=>setClient(c)}/>)}</Section></>;return <><PlanAssign workspaceId={workspaceId} clients={clients}/><div className="card"><div className="lbl2">Бібліотека вправ</div><div className="ss">Глобальні вправи + ваші власні. Додавання власних вправ лишається у стандартній вкладці «Вправи».</div></div></>}

function BusinessConsole({view,workspaceId,insights,analytics,invites,reload}){const [client,setClient]=useState(null);if(client)return <ClientDetail client={client} workspaceId={workspaceId} onBack={()=>setClient(null)}/>;const trainers=insights?.trainers||[],clients=insights?.clients||[],billing=insights?.billing,subs=insights?.subscriptions||[];if(view==='home')return <><div className="card"><div className="lbl2">VARANGYM · Business</div><div className="big" style={{fontSize:26}}>{insights?.workspace?.name||'Організація'}</div><div className="ss">Команда, клієнти, поточний тариф і активність.</div></div><div className="grid2"><Metric value={trainers.length} label="тренерів"/><Metric value={clients.length} label="клієнтів"/><Metric value={billing?.plan_code||'—'} label="поточний план" note={subs[0]?.status||''}/><Metric value={money(insights?.revenue?.month_cents)} label="дохід / місяць"/></div></>;if(view==='people')return <><Section title={`Тренери · ${trainers.length}`}>{trainers.map(t=><Row key={t.id} icon="personCircle" title={t.display_name} subtitle={t.email||''} value={`${t.clients||0} клієнтів`}/>)}</Section><Section title={`Клієнти · ${clients.length}`}>{clients.map(c=><Row key={c.id} icon="personCircle" title={c.display_name} subtitle={c.email||''} value={`${c.workouts_30d||0} / 30д`} accessory="chevron" onClick={()=>setClient(c)}/>)}</Section><InviteBox mode="business" workspaceId={workspaceId} invites={invites} reload={reload}/></>;if(view==='dashboard')return <><div className="grid2"><Metric value={billing?.plan_metadata?.label||billing?.plan_code||'—'} label="тариф"/><Metric value={subs[0]?.status||'—'} label="статус"/><Metric value={date(subs[0]?.trial_ends_at||subs[0]?.current_period_end)} label="наступна дата"/><Metric value={money(insights?.revenue?.lifetime_cents)} label="дохід за весь час"/></div><PlanAssign workspaceId={workspaceId} clients={clients}/></>;if(view==='stats')return <><div className="card"><div className="lbl2">Активність організації</div><Bars rows={analytics?.daily||[]}/></div><Section title="Клієнти · прогрес">{clients.map(c=><Row key={c.id} icon="chart" title={c.display_name} subtitle={`${c.workouts_30d||0} тренувань / 30д`} value={date(c.last_workout_at)} accessory="chevron" onClick={()=>setClient(c)}/>)}</Section></>;return <><PlanAssign workspaceId={workspaceId} clients={clients}/><div className="card"><div className="lbl2">Вправи організації</div><div className="ss">Організація може створювати власні вправи й використовувати глобальну бібліотеку для планів клієнтів.</div></div></>}

export default function RoleConsole({mode}){
  const nav=useNavigate(),loc=useLocation(),toast=useUI(s=>s.toast);const view=viewOf(loc.search);const [identity,setIdentity]=useState(null),[data,setData]=useState(null),[analytics,setAnalytics]=useState(null),[invites,setInvites]=useState([]),[err,setErr]=useState(''),[loading,setLoading]=useState(true),[workspaceId,setWorkspaceId]=useState('')
  const access=useMemo(()=>platformAccess(identity),[identity]);const tSpaces=useMemo(()=>trainerMemberships(identity),[identity]);const bSpaces=useMemo(()=>businessMemberships(identity),[identity]);const spaces=mode==='business'?bSpaces:tSpaces
  useEffect(()=>{setRoleMode(mode);loadPlatformIdentity().then(me=>{setIdentity(me);const ss=mode==='business'?businessMemberships(me):trainerMemberships(me);setWorkspaceId(v=>v||ss[0]?.workspace_id||'')}).catch(e=>setErr(e.message))},[mode])
  const allowed=identity&&((mode==='admin'&&access.platformAdmin)||(mode==='business'&&access.business)||(mode==='trainer'&&access.trainer))
  const load=async()=>{if(!identity||!allowed)return;setLoading(true);setErr('');try{if(mode==='admin'){const [i,a,c]=await Promise.all([api('/api/insights/admin'),api('/api/analytics/admin?days=30'),api('/api/invites')]);setData(i);setAnalytics(a);setInvites(c.invites||[])}else if(mode==='business'){if(!workspaceId)throw new Error('Немає business workspace');const [i,a,c]=await Promise.all([api(`/api/insights/workspace?workspaceId=${encodeURIComponent(workspaceId)}`),api(`/api/analytics/business?days=30&workspaceId=${encodeURIComponent(workspaceId)}`),api(`/api/invites?workspaceId=${encodeURIComponent(workspaceId)}`)]);setData(i);setAnalytics(a);setInvites(c.invites||[])}else{if(!workspaceId)throw new Error('Немає workspace тренера');const [o,a,c]=await Promise.all([api(`/api/coach/clients?workspaceId=${encodeURIComponent(workspaceId)}`),api(`/api/analytics/coach?days=30&workspaceId=${encodeURIComponent(workspaceId)}`),api(`/api/invites?workspaceId=${encodeURIComponent(workspaceId)}`)]);setData(o);setAnalytics(a);setInvites(c.invites||[])}}catch(e){setErr(e.message||'Помилка')}finally{setLoading(false)}}
  useEffect(()=>{if(allowed)load()},[allowed,workspaceId,mode])
  if(identity&&!allowed){nav('/home',{replace:true});return null}
  const label=mode==='admin'?'Адмін':mode==='business'?'Бізнес':'Тренер'
  return <div className="narrow"><div className="hdr"><button className="iconbtn" onClick={()=>{setRoleMode(null);nav('/home')}} aria-label="Клієнтський режим"><Icon name="chevronLeft"/></button><div style={{flex:1,marginLeft:10}}><h1>{label}</h1><div className="sub">{identity?.user?.display_name||''} · VARANGYM</div></div><button className="iconbtn" onClick={load} aria-label="Оновити"><Icon name="reset"/></button></div>{spaces.length>1&&<div className="card" style={{padding:8}}><select className="field" value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}>{spaces.map(x=><option key={`${x.workspace_id}:${x.role}`} value={x.workspace_id}>{x.workspace_name} · {x.role}</option>)}</select></div>}{loading&&!data?<div className="empty">Завантаження…</div>:err?<ErrorBox text={err} retry={load}/>:mode==='admin'?<AdminConsole view={view} data={data} analytics={analytics} invites={invites} reload={load}/>:mode==='business'?<BusinessConsole view={view} workspaceId={workspaceId} insights={data} analytics={analytics} invites={invites} reload={load}/>:<TrainerConsole view={view} workspaceId={workspaceId} overview={data} analytics={analytics} invites={invites} reload={load}/>}</div>
}
