import { baseLang, getLang } from './i18n-core.js'

const EN={
  language:'Language',choosePlan:'Choose plan',plansPricing:'Plans & pricing',manageSubscription:'Manage subscription',currentPlan:'Current plan',noPlan:'No active plan',trialUntil:'Trial until {0}',paidUntil:'Paid until {0}',nextPayment:'Next payment {0}',active:'Active',trial:'Trial',cancelsAtEnd:'Cancels at period end',changePlan:'Change plan',signOut:'Sign out',signOutAll:'Sign out on all devices',normalMode:'Training mode',adminPanel:'Admin panel',businessPanel:'Business panel',coachPanel:'Coach panel',settings:'Settings',account:'Account',mode:'Mode',loginTagline:'Your plan. Your training. Your progress.',createFree:'Create account · 30 days free',invite:'I have an invite code',continueGuest:'Continue without account',trialNote:'30-day trial. No automatic charge without a paid subscription.',pickPlanTitle:'Choose the VARANGYM that fits you',pickPlanSub:'Swipe between Solo, Coach and Business. You can upgrade later without losing your data.',startTrial:'Start 30-day trial',selectPlan:'Select plan',connected:'Current',paymentSoon:'Payments coming soon',monthly:'per month',oneTime:'one-time payment',popular:'POPULAR',soloAudience:'For your own training',soloPitch:'Everything you need to train consistently and see real progress.',coachAudience:'For personal trainers',coachPitch:'Clients, programs and progress in one professional workspace.',businessAudience:'For studios, gyms and teams',businessPitch:'Run trainers, clients, access and analytics from one place.',soloF1:'Plans, calendar and workouts',soloF2:'Progress, weight and personal records',soloF3:'Full exercise library and offline media',coachF1:'Client management and detailed progress',coachF2:'A separate program for every client',coachF3:'Invites, analytics and access control',businessF1:'Trainer and client management',businessF2:'Team dashboards and financial analytics',businessF3:'Roles, access and scalable limits',subscriptionTitle:'Subscription',subscriptionSub:'Your access, billing and plan in one place',benefits:'Included',billingStatus:'Billing status',renews:'Renews',trialEnds:'Trial ends',price:'Price',capacity:'Capacity',allPlans:'All plans',close:'Close',back:'Back',profileMode:'Training profile',roleModeActive:'{0} mode is active',logoutConfirm:'Sign out from this device?',logoutAllConfirm:'End this profile’s sessions on every device?',yesSignOut:'Sign out',yesSignOutAll:'Sign out everywhere'
}
const UK={language:'Мова',choosePlan:'Обрати тариф',plansPricing:'Тарифи й ціни',manageSubscription:'Керування підпискою',currentPlan:'Поточний тариф',noPlan:'Немає активного тарифу',trialUntil:'Trial до {0}',paidUntil:'Оплачено до {0}',nextPayment:'Наступний платіж {0}',active:'Активна',trial:'Пробний період',cancelsAtEnd:'Скасується наприкінці періоду',changePlan:'Змінити тариф',signOut:'Вийти',signOutAll:'Вийти на всіх пристроях',normalMode:'Режим тренувань',adminPanel:'Admin панель',businessPanel:'Business панель',coachPanel:'Coach панель',settings:'Налаштування',account:'Акаунт',mode:'Режим',loginTagline:'Твій план. Твої тренування. Твій прогрес.',createFree:'Створити акаунт · 30 днів безкоштовно',invite:'Маю код запрошення',continueGuest:'Продовжити без акаунта',trialNote:'30 днів безкоштовно. Без автоматичного списання без платної підписки.',pickPlanTitle:'Обери свій VARANGYM',pickPlanSub:'Гортай Solo, Coach і Business. Тариф можна змінити пізніше без втрати даних.',startTrial:'Почати 30 днів безкоштовно',selectPlan:'Обрати тариф',connected:'Поточний',paymentSoon:'Оплата скоро',monthly:'на місяць',oneTime:'разова оплата',popular:'ПОПУЛЯРНИЙ',soloAudience:'Для власних тренувань',soloPitch:'Усе для системних тренувань і зрозумілого прогресу.',coachAudience:'Для персональних тренерів',coachPitch:'Клієнти, програми та прогрес в одному професійному просторі.',businessAudience:'Для студій, залів і команд',businessPitch:'Тренери, клієнти, доступи та аналітика в одному місці.',soloF1:'Плани, календар і тренування',soloF2:'Прогрес, вага та особисті рекорди',soloF3:'Повна бібліотека вправ і офлайн-медіа',coachF1:'Клієнти та детальна статистика',coachF2:'Окрема програма для кожного клієнта',coachF3:'Запрошення, аналітика та контроль доступу',businessF1:'Керування тренерами й клієнтами',businessF2:'Командні дашборди та фінансова аналітика',businessF3:'Ролі, доступи й масштабовані ліміти',subscriptionTitle:'Підписка',subscriptionSub:'Доступ, оплата й тариф в одному місці',benefits:'Що входить',billingStatus:'Стан оплати',renews:'Продовження',trialEnds:'Trial закінчується',price:'Ціна',capacity:'Ліміти',allPlans:'Усі тарифи',close:'Закрити',back:'Назад',profileMode:'Звичайний режим тренувань',roleModeActive:'Активний режим: {0}',logoutConfirm:'Вийти з цього пристрою?',logoutAllConfirm:'Завершити сесії цього профілю на всіх пристроях?',yesSignOut:'Вийти',yesSignOutAll:'Вийти всюди'}
const DE={language:'Sprache',choosePlan:'Tarif wählen',plansPricing:'Tarife & Preise',manageSubscription:'Abo verwalten',currentPlan:'Aktueller Tarif',noPlan:'Kein aktiver Tarif',trialUntil:'Testphase bis {0}',paidUntil:'Bezahlt bis {0}',nextPayment:'Nächste Zahlung {0}',active:'Aktiv',trial:'Testphase',cancelsAtEnd:'Endet zum Periodenende',changePlan:'Tarif wechseln',signOut:'Abmelden',signOutAll:'Auf allen Geräten abmelden',normalMode:'Trainingsmodus',adminPanel:'Admin-Bereich',businessPanel:'Business-Bereich',coachPanel:'Coach-Bereich',settings:'Einstellungen',account:'Konto',mode:'Modus',loginTagline:'Dein Plan. Dein Training. Dein Fortschritt.',createFree:'Konto erstellen · 30 Tage kostenlos',invite:'Ich habe einen Einladungscode',continueGuest:'Ohne Konto fortfahren',trialNote:'30 Tage kostenlos. Keine automatische Abbuchung ohne bezahltes Abo.',pickPlanTitle:'Wähle dein VARANGYM',pickPlanSub:'Wechsle zwischen Solo, Coach und Business. Upgrade später ohne Datenverlust.',startTrial:'30 Tage kostenlos starten',selectPlan:'Tarif wählen',connected:'Aktuell',paymentSoon:'Zahlungen bald verfügbar',monthly:'pro Monat',oneTime:'einmalig',popular:'BELIEBT',soloAudience:'Für dein eigenes Training',soloPitch:'Alles für konsequentes Training und sichtbaren Fortschritt.',coachAudience:'Für Personal Trainer',coachPitch:'Kunden, Programme und Fortschritt in einem professionellen Bereich.',businessAudience:'Für Studios, Gyms und Teams',businessPitch:'Trainer, Kunden, Zugriffe und Analysen zentral verwalten.',soloF1:'Pläne, Kalender und Workouts',soloF2:'Fortschritt, Gewicht und Rekorde',soloF3:'Komplette Übungsbibliothek und Offline-Medien',coachF1:'Kundenverwaltung und Detailfortschritt',coachF2:'Eigenes Programm für jeden Kunden',coachF3:'Einladungen, Analysen und Zugriffskontrolle',businessF1:'Trainer- und Kundenverwaltung',businessF2:'Team-Dashboards und Finanzanalyse',businessF3:'Rollen, Zugriffe und skalierbare Limits',subscriptionTitle:'Abonnement',subscriptionSub:'Zugriff, Abrechnung und Tarif an einem Ort',benefits:'Enthalten',billingStatus:'Abrechnungsstatus',renews:'Verlängert sich',trialEnds:'Testphase endet',price:'Preis',capacity:'Limits',allPlans:'Alle Tarife',close:'Schließen',back:'Zurück',profileMode:'Trainingsprofil',roleModeActive:'{0}-Modus aktiv',logoutConfirm:'Auf diesem Gerät abmelden?',logoutAllConfirm:'Alle Sitzungen dieses Profils beenden?',yesSignOut:'Abmelden',yesSignOutAll:'Überall abmelden'}
const RU={language:'Язык',choosePlan:'Выбрать тариф',plansPricing:'Тарифы и цены',manageSubscription:'Управление подпиской',currentPlan:'Текущий тариф',noPlan:'Нет активного тарифа',trialUntil:'Пробный период до {0}',paidUntil:'Оплачено до {0}',nextPayment:'Следующий платёж {0}',active:'Активна',trial:'Пробный период',cancelsAtEnd:'Отменится в конце периода',changePlan:'Сменить тариф',signOut:'Выйти',signOutAll:'Выйти на всех устройствах',normalMode:'Режим тренировок',adminPanel:'Admin панель',businessPanel:'Business панель',coachPanel:'Coach панель',settings:'Настройки',account:'Аккаунт',mode:'Режим',loginTagline:'Твой план. Твои тренировки. Твой прогресс.',createFree:'Создать аккаунт · 30 дней бесплатно',invite:'У меня есть код приглашения',continueGuest:'Продолжить без аккаунта',trialNote:'30 дней бесплатно. Без автосписания без платной подписки.',pickPlanTitle:'Выбери свой VARANGYM',pickPlanSub:'Листай Solo, Coach и Business. Тариф можно изменить позже без потери данных.',startTrial:'Начать 30 дней бесплатно',selectPlan:'Выбрать тариф',connected:'Текущий',paymentSoon:'Оплата скоро',monthly:'в месяц',oneTime:'разовая оплата',popular:'ПОПУЛЯРНЫЙ',soloAudience:'Для своих тренировок',soloPitch:'Всё для системных тренировок и понятного прогресса.',coachAudience:'Для персональных тренеров',coachPitch:'Клиенты, программы и прогресс в одном профессиональном пространстве.',businessAudience:'Для студий, залов и команд',businessPitch:'Тренеры, клиенты, доступы и аналитика в одном месте.',soloF1:'Планы, календарь и тренировки',soloF2:'Прогресс, вес и личные рекорды',soloF3:'Полная библиотека упражнений и офлайн-медиа',coachF1:'Клиенты и подробная статистика',coachF2:'Отдельная программа для каждого клиента',coachF3:'Приглашения, аналитика и контроль доступа',businessF1:'Управление тренерами и клиентами',businessF2:'Командные дашборды и финансовая аналитика',businessF3:'Роли, доступы и масштабируемые лимиты',subscriptionTitle:'Подписка',subscriptionSub:'Доступ, оплата и тариф в одном месте',benefits:'Что входит',billingStatus:'Статус оплаты',renews:'Продление',trialEnds:'Пробный период заканчивается',price:'Цена',capacity:'Лимиты',allPlans:'Все тарифы',close:'Закрыть',back:'Назад',profileMode:'Обычный режим тренировок',roleModeActive:'Активный режим: {0}',logoutConfirm:'Выйти с этого устройства?',logoutAllConfirm:'Завершить сессии профиля на всех устройствах?',yesSignOut:'Выйти',yesSignOutAll:'Выйти везде'}

const FALLBACKS={de:DE,'de-CH':DE,uk:UK,ru:RU}
const QUICK={
  es:{language:'Idioma',choosePlan:'Elegir plan',manageSubscription:'Gestionar suscripción',currentPlan:'Plan actual',changePlan:'Cambiar plan',signOut:'Cerrar sesión',signOutAll:'Cerrar sesión en todos los dispositivos',loginTagline:'Tu plan. Tu entrenamiento. Tu progreso.',createFree:'Crear cuenta · 30 días gratis',invite:'Tengo un código de invitación',plansPricing:'Planes y precios',pickPlanTitle:'Elige tu VARANGYM',startTrial:'Empezar 30 días gratis',selectPlan:'Elegir plan'},
  fr:{language:'Langue',choosePlan:'Choisir un forfait',manageSubscription:'Gérer l’abonnement',currentPlan:'Forfait actuel',changePlan:'Changer de forfait',signOut:'Se déconnecter',signOutAll:'Se déconnecter partout',loginTagline:'Votre plan. Votre entraînement. Vos progrès.',createFree:'Créer un compte · 30 jours gratuits',invite:'J’ai un code d’invitation',plansPricing:'Forfaits et tarifs',pickPlanTitle:'Choisissez votre VARANGYM',startTrial:'Commencer 30 jours gratuits',selectPlan:'Choisir'},
  it:{language:'Lingua',choosePlan:'Scegli piano',manageSubscription:'Gestisci abbonamento',currentPlan:'Piano attuale',changePlan:'Cambia piano',signOut:'Esci',signOutAll:'Esci da tutti i dispositivi',loginTagline:'Il tuo piano. Il tuo allenamento. I tuoi progressi.',createFree:'Crea account · 30 giorni gratis',invite:'Ho un codice invito',plansPricing:'Piani e prezzi',pickPlanTitle:'Scegli il tuo VARANGYM',startTrial:'Inizia 30 giorni gratis',selectPlan:'Scegli'},
  pl:{language:'Język',choosePlan:'Wybierz plan',manageSubscription:'Zarządzaj subskrypcją',currentPlan:'Aktualny plan',changePlan:'Zmień plan',signOut:'Wyloguj',signOutAll:'Wyloguj na wszystkich urządzeniach',loginTagline:'Twój plan. Twój trening. Twój postęp.',createFree:'Utwórz konto · 30 dni za darmo',invite:'Mam kod zaproszenia',plansPricing:'Plany i ceny',pickPlanTitle:'Wybierz swój VARANGYM',startTrial:'Zacznij 30 dni za darmo',selectPlan:'Wybierz'},
  tr:{language:'Dil',choosePlan:'Plan seç',manageSubscription:'Aboneliği yönet',currentPlan:'Mevcut plan',changePlan:'Planı değiştir',signOut:'Çıkış yap',signOutAll:'Tüm cihazlardan çıkış yap',loginTagline:'Planın. Antrenmanın. İlerlemen.',createFree:'Hesap oluştur · 30 gün ücretsiz',invite:'Davet kodum var',plansPricing:'Planlar ve fiyatlar',pickPlanTitle:'VARANGYM planını seç',startTrial:'30 gün ücretsiz başla',selectPlan:'Plan seç'},
  pt:{language:'Idioma',choosePlan:'Escolher plano',manageSubscription:'Gerir subscrição',currentPlan:'Plano atual',changePlan:'Alterar plano',signOut:'Terminar sessão',signOutAll:'Terminar sessão em todos os dispositivos',loginTagline:'O teu plano. O teu treino. O teu progresso.',createFree:'Criar conta · 30 dias grátis',invite:'Tenho um código de convite',plansPricing:'Planos e preços',pickPlanTitle:'Escolhe o teu VARANGYM',startTrial:'Começar 30 dias grátis',selectPlan:'Escolher'},
  'pt-BR':{language:'Idioma',choosePlan:'Escolher plano',manageSubscription:'Gerenciar assinatura',currentPlan:'Plano atual',changePlan:'Trocar plano',signOut:'Sair',signOutAll:'Sair de todos os dispositivos',loginTagline:'Seu plano. Seu treino. Seu progresso.',createFree:'Criar conta · 30 dias grátis',invite:'Tenho um código de convite',plansPricing:'Planos e preços',pickPlanTitle:'Escolha seu VARANGYM',startTrial:'Começar 30 dias grátis',selectPlan:'Escolher'},
  zh:{language:'语言',choosePlan:'选择方案',manageSubscription:'管理订阅',currentPlan:'当前方案',changePlan:'更改方案',signOut:'退出登录',signOutAll:'在所有设备上退出',loginTagline:'你的计划。你的训练。你的进步。',createFree:'创建账户 · 免费30天',invite:'我有邀请码',plansPricing:'方案与价格',pickPlanTitle:'选择你的 VARANGYM',startTrial:'开始30天免费试用',selectPlan:'选择方案'},
  ko:{language:'언어',choosePlan:'요금제 선택',manageSubscription:'구독 관리',currentPlan:'현재 요금제',changePlan:'요금제 변경',signOut:'로그아웃',signOutAll:'모든 기기에서 로그아웃',loginTagline:'당신의 계획. 당신의 훈련. 당신의 성장.',createFree:'계정 만들기 · 30일 무료',invite:'초대 코드가 있어요',plansPricing:'요금제 및 가격',pickPlanTitle:'VARANGYM 선택',startTrial:'30일 무료 시작',selectPlan:'선택'},
  hi:{language:'भाषा',choosePlan:'प्लान चुनें',manageSubscription:'सदस्यता प्रबंधित करें',currentPlan:'मौजूदा प्लान',changePlan:'प्लान बदलें',signOut:'साइन आउट',signOutAll:'सभी डिवाइस से साइन आउट',loginTagline:'आपकी योजना। आपका प्रशिक्षण। आपकी प्रगति।',createFree:'खाता बनाएँ · 30 दिन मुफ़्त',invite:'मेरे पास आमंत्रण कोड है',plansPricing:'प्लान और कीमतें',pickPlanTitle:'अपना VARANGYM चुनें',startTrial:'30 दिन मुफ़्त शुरू करें',selectPlan:'चुनें'},
  th:{language:'ภาษา',choosePlan:'เลือกแพ็กเกจ',manageSubscription:'จัดการสมาชิก',currentPlan:'แพ็กเกจปัจจุบัน',changePlan:'เปลี่ยนแพ็กเกจ',signOut:'ออกจากระบบ',signOutAll:'ออกจากระบบทุกอุปกรณ์',loginTagline:'แผนของคุณ การฝึกของคุณ ความก้าวหน้าของคุณ',createFree:'สร้างบัญชี · ฟรี 30 วัน',invite:'ฉันมีรหัสเชิญ',plansPricing:'แพ็กเกจและราคา',pickPlanTitle:'เลือก VARANGYM ของคุณ',startTrial:'เริ่มใช้ฟรี 30 วัน',selectPlan:'เลือก'},
  hu:{language:'Nyelv',choosePlan:'Csomag választása',manageSubscription:'Előfizetés kezelése',currentPlan:'Jelenlegi csomag',changePlan:'Csomagváltás',signOut:'Kijelentkezés',signOutAll:'Kijelentkezés minden eszközről',loginTagline:'A terved. Az edzésed. A fejlődésed.',createFree:'Fiók létrehozása · 30 nap ingyen',invite:'Van meghívókódom',plansPricing:'Csomagok és árak',pickPlanTitle:'Válaszd a VARANGYM csomagod',startTrial:'30 nap ingyen',selectPlan:'Kiválasztás'}
}

export function productText(key,...args){
  const lang=getLang(), base=baseLang(lang)
  const dict={...EN,...(FALLBACKS[lang]||FALLBACKS[base]||{}),...(QUICK[lang]||QUICK[base]||{})}
  let out=dict[key]??EN[key]??key
  args.forEach((v,i)=>{out=String(out).replaceAll(`{${i}}`,v)})
  return out
}
